version: "3"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_lab
    ports:
      - "27017:27017"

  hadoop-master:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    environment:
      - CLUSTER_NAME=test
    ports:
      - "9870:9870"
      - "9000:9000"

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    environment:
      - SERVICE_PRECONDITION=namenode:9870
    depends_on:
      - hadoop-master

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    depends_on:
      - hadoop-master
      - datanode

  nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager
    depends_on:
      - resourcemanager

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive_server
    ports:
      - "10000:10000"
